module(
    name = "scala-bazel",
    version = "",
)

bazel_dep(name = "rules_scala", version = "7.1.2")
bazel_dep(name = "rules_java", version = "8.12.0")
bazel_dep(name = "rules_jvm_external", version = "6.8")

scala_config = use_extension(
    "@rules_scala//scala/extensions:config.bzl",
    "scala_config",
)
scala_config.settings(scala_version = "3.3.6")

# 2.13.16 works
#scala_config.settings(scala_version = "2.13.16")
use_repo(scala_config, "rules_scala_config")

scala_deps = use_extension(
    "@rules_scala//scala/extensions:deps.bzl",
    "scala_deps",
)
scala_deps.scala()
scala_deps.scalatest()
scala_deps.settings(
    fetch_sources = True,
)
scala_deps.scala_proto(
    default_gen_opts = [
        "grpc",
        "flat_package",
        "scala3_sources",
    ],
)

scala_protoc = use_extension(
    "@rules_scala//scala/extensions:protoc.bzl",
    "scala_protoc",
    dev_dependency = True,
)
use_repo(scala_protoc, "rules_scala_protoc_toolchains")

# Register this toolchain before any others in the file. Still safe even when
# `--incompatible_enable_proto_toolchain_resolution` is `False`.
register_toolchains(
    "@rules_scala_protoc_toolchains//...:all",
    dev_dependency = True,
)

bazel_dep(
    name = "protobuf",
    version = "32.0",
    repo_name = "com_google_protobuf",
)
single_version_override(
    module_name = "protobuf",
    patch_strip = 1,
    patches = ["//:protobuf.patch"],
    version = "32.0",
)

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "io.grpc:grpc-api:1.75.0",
        "io.grpc:grpc-netty:1.75.0",
        "io.grpc:grpc-protobuf:1.75.0",
        "io.grpc:grpc-stub:1.75.0",
    ],
    fetch_sources = True,
    known_contributing_modules = [
        "protobuf",
        "scala-bazel",
    ],
    lock_file = "//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")
